name: .NET TodoApp
on: 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore TodoApp/TodoApp.csproj
    - name: .NET Build
      run: dotnet build TodoApp/TodoApp.csproj --no-restore

  test: 
  
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
    - name: Test
      run: dotnet run TodoApp.Tests/TodoApp.Tests.csproj --no-build --verbosity normal
